package Lab_6_Pack;

import Lab_3_Pack.PrivateAuto;
import Lab_3_Pack.Record;
import Lab_5_Pack.RecordDAO;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Locale;

public class Add extends JFrame {
    private JPanel addPanel;
    private JLabel addHeader;
    private JButton ADDRECORDButton;
    private JTextField numberField;
    private JTextField modelField;
    private JTextField ownerField;
    private JTextField dateField;
    private JLabel successText;
    private JButton main;
    Record record;
    RecordDAO recordDAO = new RecordDAO();

    public Add(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(addPanel);
        this.successText.setVisible(false);
        this.pack();

        ADDRECORDButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                int num = (int) Integer.parseInt(numberField.getText());
                String mod = modelField.getText();
                String name = ownerField.getText();
                String date = dateField.getText();
                record = new Record(new PrivateAuto(num, mod, name, 1), date);
                //
                try {
                    recordDAO.create(record);
                } catch (SQLException sqlException) {
                    sqlException.printStackTrace();
                }
                successText.setVisible(true);
            }
        });

        main.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame mainPanel = new Main("Main");
                mainPanel.setBounds(615, 315, 750, 450);
                mainPanel.setVisible(true);
                dispose();

            }
        });
    }

    public static void main(String[] args) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addPanel = new JPanel();
        addPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 2, new Insets(0, 0, 0, 0), -1, -1));
        addPanel.setBackground(new Color(-14407116));
        addHeader = new JLabel();
        Font addHeaderFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 24, addHeader.getFont());
        if (addHeaderFont != null) addHeader.setFont(addHeaderFont);
        addHeader.setForeground(new Color(-7357510));
        addHeader.setText("ADD NEW RECORD");
        addPanel.add(addHeader, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-6841669));
        label1.setText("Enter Number Of Auto");
        addPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numberField = new JTextField();
        numberField.setBackground(new Color(-7357510));
        Font numberFieldFont = this.$$$getFont$$$("Source Code Pro", Font.BOLD, 16, numberField.getFont());
        if (numberFieldFont != null) numberField.setFont(numberFieldFont);
        numberField.setForeground(new Color(-14407116));
        addPanel.add(numberField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 16, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-6841669));
        label2.setText("Enter Car Model");
        addPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 16, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-6841669));
        label3.setText("Date Of Enter ");
        addPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 16, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-6841669));
        label4.setText("Enter Owner Name ");
        addPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modelField = new JTextField();
        modelField.setBackground(new Color(-7357510));
        Font modelFieldFont = this.$$$getFont$$$("Source Code Pro", Font.BOLD, 16, modelField.getFont());
        if (modelFieldFont != null) modelField.setFont(modelFieldFont);
        modelField.setForeground(new Color(-14407116));
        addPanel.add(modelField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        ownerField = new JTextField();
        ownerField.setBackground(new Color(-7357510));
        Font ownerFieldFont = this.$$$getFont$$$("Source Code Pro", Font.BOLD, 16, ownerField.getFont());
        if (ownerFieldFont != null) ownerField.setFont(ownerFieldFont);
        ownerField.setForeground(new Color(-14407116));
        addPanel.add(ownerField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        dateField = new JTextField();
        dateField.setBackground(new Color(-7357510));
        Font dateFieldFont = this.$$$getFont$$$("Source Code Pro", Font.BOLD, 16, dateField.getFont());
        if (dateFieldFont != null) dateField.setFont(dateFieldFont);
        dateField.setForeground(new Color(-14407116));
        addPanel.add(dateField, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        successText = new JLabel();
        Font successTextFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 19, successText.getFont());
        if (successTextFont != null) successText.setFont(successTextFont);
        successText.setForeground(new Color(-6841669));
        successText.setText("YOUR RECORD WAS APPENDED ");
        addPanel.add(successText, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        main = new JButton();
        main.setBackground(new Color(-7357510));
        Font mainFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 18, main.getFont());
        if (mainFont != null) main.setFont(mainFont);
        main.setForeground(new Color(-13223861));
        main.setText("MAIN MENU");
        addPanel.add(main, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ADDRECORDButton = new JButton();
        ADDRECORDButton.setBackground(new Color(-7357510));
        Font ADDRECORDButtonFont = this.$$$getFont$$$("Roboto Light", Font.PLAIN, 18, ADDRECORDButton.getFont());
        if (ADDRECORDButtonFont != null) ADDRECORDButton.setFont(ADDRECORDButtonFont);
        ADDRECORDButton.setForeground(new Color(-13223861));
        ADDRECORDButton.setText("ADD RECORD");
        addPanel.add(ADDRECORDButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addPanel;
    }

}
